name: YVtils-DC
version: ${project.version}
main: yv.tils.dc.DiscordPlugin
api-version: 1.18
authors: [ WolfiiYV ]
contributor: [ SlWed, black_Kittys, SilverZer0 ]
description: Discord part of the YVtils-SMP plugin
website: yvnetwork.de
